= 自立循環型住宅への設計ガイドライン

:Revision: 1.0

=== 5.2 換気設備計画

! 挿絵

平成15 年の建築基準法の改正以降、事実上すべての住宅ではシックハウス対策としての機械換気設備の導入が義務づけられています。ホルムアルデヒド等を発散する建材の使用の制限と併せて、年間を通じて、居室に1時間当たり0.5 回以上の有効換気量が求められています。 +
この機械換気に要するエネルギーをいかに節約するかが、また機械換気にともない生じる暖房負荷をいかに低減するかが、換気設備の省エネルギー技術として重要です。

==== 5.2.1 換気設備計画の目的とポイント

- 換気設備計画は、夏期や冬期に開口部（窓）を閉め切った状態においても、建築基準法で求められている0.5 回/h 以上の換気量を確保し、住宅内の空気環境を安全・快適に保つことを目的とした主として全般換気に関する技術です。
- 便所、浴室、台所などの水まわり等に設置する局所換気設備は、臭気、水蒸気、排ガス、油分等を排出し、室内空間を衛生的に保つ目的があります。ただし、前記の全般換気に比べ換気量がはるかに大きいので、風量の設定や外気取り入れ経路の考慮などの適切な計画が必要となります。
- 冬期において、室内と屋外の温度差を利用した温度差換気を効果的に利用すれば、機械換気で消費するエネルギーを削減することができます（温度差利用のハイブリッド換気）。
- 冬期の換気では、低温の外気が室内に流入し、住まい手に直接外気が当たることによる不快感が発生することがあります（コールド・ドラフト、p.239 参照）。その点の対策を考慮することで、快適性を維持することができます。
- 換気システムにはダクト式換気システムと壁付け式換気システムがあり、それらの省エネルギーのためには、ダクトや外部フードに起因する圧力損失の低減、高効率ファンの採用および換気量を長期にわたり維持するためのメンテナンスを意識した計画と住まい手への注意喚起が重要です。

==== 5.2.2 換気設備計画による省エネルギー目標レベル
===== 1 目標レベルの定義
- 換気設備計画による省エネルギー目標レベルは、以下のレベル1 から4 までとし、住宅全体の換気設備に消費されるエネルギーの削減率を表します。
- 2010 年頃における標準的な換気エネルギー消費量は5（Ⅳ a）地域、6（Ⅳ b）地域ともに4.6GJで、5（Ⅳ a）地域で居室間歇暖冷房時のエネルギー消費量合計値の4.6%、6（Ⅳ b）地域で5.1%となります（6.1 参照）。

[cols='1,2']
|======
| レベル－ | 換気エネルギー増加
| レベル0 | 換気エネルギー削減　　なし
| レベル1 | 換気エネルギー削減率　5％～ 10%
| レベル2 | 換気エネルギー削減率　15％～ 25%
| レベル3 | 換気エネルギー削減率　30％～ 40%
| レベル4 | 換気エネルギー削減率　45％～ 55%
|======

- レベル0 は「壁付け換気システム（第三種）において、換気設備計画の設計上の工夫をしない（省エネルギー手法を採用しない）」場合に相当します。
- 「レベル－」は適用する換気方式における換気エネルギー消費量が標準値（レベル0）となる換気エネルギー消費量より増加する場合です。
